### ISSUE TITLE
Sensitivity and Structure Edge Contributions Are Switched

### ISSUE THREAD

**Issue by DGendoo** [bhklab/DNF-webapp#10]
I have been checking the edge contribution as shown when clicking on an edge between two drugs. The actual numbers (extracted from the SNF affinity matrices) seems to be correct. HOWEVER, the labels between Structure and Sensitivity are switched!
For example, when I look at the edge weight (from our code), between Imatinib and Nilotinib, I get 0.78, 0.57, and 0.02 for Structure, Sensitivity, and Perturbation, respectively.
On the webapp however, these same numbers are labelled as Sensitivity, Structure, and Perturbation.
Please double-check this

**Comment by chrchung** [comment]
Fixed
