### ISSUE TITLE
Search for drug in the full/exemplar network displays only community

### ISSUE THREAD

**Issue by bhaibeka** [bhklab/DNF-webapp#6]
When users search for a drug, is there a way to highlight it in the network that is displayed instead of jumping to the community where that drug is?

In other words, if users are viewing the Full Network, just a highlight of the searched drug in the full network (like blinking light green or an animation) would be cool.

**Comment by dknyxh** [comment]
If it is in exemplar view, is the `search` function only searching for the nodes in exemplar view? Or it is searching for all the nodes available for the current network?

If it is the second case, what should we do if there is a search result but no such node in the exemplar view? Should it still jump to community?

**Comment by bhaibeka** [comment]
In exemplar view, it should search for all the drugs in the network and it is ok to jump to the community directly.

For the full network, it should just highlight where the drug is in the full network, no jump to community
